{% set data = load_setup_py_data() %}
package:
  name: grelease
  version: v0.0.8

source:
  path: ..

build:
  number: 0
  script: python -m pip install . -vv

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - grelease

about:
  url: https://github.com/zhangming/github-release
  license: Apache-2.0
  license_file: LICENSE
  summary: hi