{% set data = load_setup_py_data(setup_file='../setup.py') %}
package:
  name: grelease
  version: {{ data['version'] }}

source:
  path: .

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - grelease

about:
  url: https://github.com/zhangming/github-release
  license: Apache-2.0
  license_file: LICENSE
  summary: hi